timezone: Asia/Shanghai
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
kramdown:
  input: GFM # GitHub Flavored Markdown
permalink: /:title/
url: danshuiyulx.github.io
#url: http://www.neulx.com
name: 李翔的个人博客,记录生活、学术的的点点滴滴。
author: danshuiyulx
email: 1516505135@qq.com
qq: 1516505135
isso_comments: 
beian: 
cnzz:
ga: UA-77551377-1 #Google Analytics
weibo:
github: danshuiyuLX
highlighter: rouge
safe: true
paginate: 20
about: "这里是李翔的个人博客。"
repository: danshuiyuLX/danshuiyulx.github.io
plugins:
- jekyll-paginate
- jekyll-github-metadata
- jekyll-mentions
- jekyll-redirect-from
- jekyll-sitemap
- jemoji

